version: '3'

services:
  web:
    container_name: app
    build:
      context: .
      target: builder
    stop_signal: SIGINT
    restart: on-failure
    ports: 
      - '80:5000'
    volumes:
      - ./:/app
